### ISSUE TITLE
Create vsix package for VS Community

### ISSUE THREAD

**Issue by hbcpn** [garrettjohnson/vscode-lava-syntax#1]
@garrettjohnson would you consider creating a package that would work for Visual Studio Community as well, and/or adding it to that separate marketplace? I downloaded the vsix file off of the VS Code marketplace and then tried to install it with the vsixinstaller.exe and it surely knows the difference in editions once it's an encoded packaged installation file.

![image](https://user-images.githubusercontent.com/44647719/92619083-108ad300-f28f-11ea-8105-58d120650442.png)
![image](https://user-images.githubusercontent.com/44647719/92618846-c7d31a00-f28e-11ea-9672-21f25e328ac5.png)

**Comment by garrettjohnson** [comment]
@hbcpn I'll work on creating basic language files for Visual Studio. It's a little tricky since Visual Studio uses a very different plugin architecture than VSCode. I'll keep you updated!

**Comment by hbcpn** [comment]
If the solution is, why aren't you just using VS Code vs. VS Studio Community then that's fine. I can switch IDEs. I'm just new to learning the development side and so I was starting with the free "full" version. Not sure why MS has so many variations out there.
I certainly don't want this to take up a bunch of your time if changing my dev setup is an easier path.

**Comment by garrettjohnson** [comment]
Sorry for the delay, I wanted to make sure to do all the research I possibly could...

Unfortunately full Visual Studio doesn't support importing multiple `tmLanguage` files, which means that lava files would lack syntax highlighting for HTML, CSS, SQL, LESS, etc. (I was able to create a test VSIX file but it was so severely constrained its not worth sharing.)

If you're familiar with Visual Studio, I'd recommend giving both editors a shot. Use Visual Studio for writing C# code, compiling and running Rock and use Visual Studio Code for lava and Rock theme development.
